"""add competitor tracking and alerts

Revision ID: 15ad79c1ef72
Revises: 5e903273e07e
Create Date: 2026-08-11 07:26:19.411832+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ad79c1ef72'
down_revision: Union[str, None] = '5e903273e07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('threshold_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'webhook')", name='ck_alert_rules_channel'),
    sa.CheckConstraint("rule_type IN ('undercut', 'price_below', 'back_in_stock')", name='ck_alert_rules_rule_type'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('product_id != competitor_product_id', name='ck_product_competitor_not_self'),
    sa.ForeignKeyConstraint(['competitor_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'competitor_product_id', name='uq_product_competitor_pair')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('competitor_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('competitor_product_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('delivery_error', sa.String(length=2048), nullable=True),
    sa.CheckConstraint("delivery_status IN ('pending', 'sent', 'failed')", name='ck_alert_events_delivery_status'),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_events_alert_rule_id_triggered_at', 'alert_events', ['alert_rule_id', sa.text('triggered_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_alert_rule_id_triggered_at', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('product_competitors')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
